[package]
name = "jakkunight-ali"
version = "0.0.3"
description = "A simple CLI tool for matrix calculation."
edition = "2021"
license = "MIT"
author = "jakkunight"
homepage = "https://jakkunight.github.io/ali/"
repo = "https://github.com/jakkunight/ali"

[dependencies]
